{% set name = "tsl_robin_map" %}
{% set version = "0.6.3" %}
{% set sha256 = "e6654c8c2598f63eb0b1d52ff8bdf39cfcc91d81dd5d05274a6dca91241cd72f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Tessil/robin-map/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/tsl  # [unix]
    - test -f ${PREFIX}/include/tsl/robin_map.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/tsl_robin_map/tsl_robin_mapConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/tsl_robin_map/tsl_robin_mapConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\tsl\robin_map.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\tsl_robin_mapConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\tsl_robin_mapConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/Tessil/robin-map
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'C++ fast hash map and hash set using robin hood hashing'
  description: 'C++ fast hash map and hash set using robin hood hashing'
  doc_url: https://tessil.github.io/robin-map/
  dev_url: https://github.com/Tessil/robin-map

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - mfansler
